### ISSUE TITLE
Set up Azure MCP for Coding Agent

### ISSUE THREAD

**Issue by dyu1208** [dyu1208/contoso-air-automatic#1]
[Example: Azure](https://docs.github.com/en/enterprise-cloud@latest/copilot/customizing-copilot/extending-copilot-coding-agent-with-mcp#example-azure)
The [Azure MCP server](https://github.com/Azure/azure-mcp) creates a seamless connection between Copilot and key Azure services such as Azure Cosmos DB and the Azure Storage platform.

To use the Azure MCP with Copilot coding agent, you must update the repository's copilot-setup-steps.yml file to include an Azure login workflow step.

Configure OIDC in a Microsoft Entra application, trusting GitHub. See [Use the Azure Login action with OpenID Connect](https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure-openid-connect).

Add a .github/workflows/copilot-setup-steps.yml Actions workflow file in your repository if you do not already have one.

Add an Azure login step to the copilot-setup-steps workflow job.

```
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: Copilot
    steps:
      - name: Azure login
        uses: azure/login@a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0
        with:
          client-id: $
          tenant-id: $
          subscription-id: $
```
This configuration ensures the azure/login action is executed when Copilot coding agent runs.

In your repository’s Copilot environment, add secrets for your AZURE_CLIENT_ID, AZURE_TENANT_ID and AZURE_SUBSCRIPTION_ID.

Configure the Azure MCP server by adding an azure object to your MCP configuration.

```
{
  "mcpServers": {
    "Azure MCP Server": {
      "command": "npx",
      "args": [
        "-y",
        "@azure/mcp@latest",
        "server",
        "start"
      ]
    }
  }
}
```
